name: Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_S3_REGION }}
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_KEY_SECRET }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo ${{ github.event.repository.name }}
      #   run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/${{ github.event.repository.name }} --delete
      # - name: Invalidate cache
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
      - name: Save npm logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: ~/.npm/_logs